In [150]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [151]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__)

3.8.1

In [152]:
import cufflinks as cf

In [153]:
# For Notebooks
init_notebook_mode(connected=True)

In [154]:
# For offline use
cf.go_offline()

In [155]:
import os

path =  os.getcwd()
datafolder="/datos-tasa-mortalidad/"

filenames = os.listdir(path+datafolder)

In [156]:
for filename in filenames:
    if ".csv" not in filename:
        filenames.remove(filename)
print(filenames)

['Tasa_Mortalidad_Cancer_Prostata_Serie_Historica.csv', 'Tasa_Mortalidad_Suicidios_Jovenes_Serie_Historica.csv', 'Tasa_Incidencia_Paludismo_Serie_Historica.csv', 'Tasa_Mortalidad_Diabetes_Tipo_II_Serie_Historica.csv', 'Tasa_incidencia_tuberculosis_Serie_Historica.csv', 'Tasa_Mortalidad_Neonatal_Serie_Historica.csv', 'Tasa_Mortalidad_Cardiovascular_Serie_Historica.csv', 'Tasa_Mortalidad_EPOC_Serie_Historica.csv', 'Tasa_Mortalidad_Cancer_Mama_Serie_Historica.csv', 'Tasa_Letalidad_Dengue_Serie_Historica.csv', 'Tasa_Mortalidad_por_Tuberculosis_Serie_Historica.csv', 'Tasa_Mortalidad_Neoplasias_Serie_Historica.csv', 'Tasa_Mortalidad_Menores_de_5_Serie_Historica.csv', 'Tasa_Mortalidad_por_VIH-SIDA_Serie_Historica.csv', 'Tasa_Mortalidad_ATVM_Serie_Historica.csv']

In [157]:
dfs=[None]*len(filenames)
for i,filename in enumerate(filenames):
        dfs[i]=pd.read_csv(path+datafolder+filename)   

#df=pd.read_csv(path+datafolder+'Tasa_incidencia_tuberculosis_Serie_Historica.csv')

In [158]:
list(dfs[1])

['Periodo',
 'Entidad de Ocurrencia',
 'Defunciones por Suicidio',
 'Poblacion Total Adolescente',
 'Tasa de Mortalidad por Suicidio']

In [159]:
dfs[9].rename(index=str,columns={'Tasa de Letalidad por 100':'tasa de letalidad por 100 por dengue'}, inplace=True)

In [160]:
import string
from unidecode import unidecode

In [161]:

for i in range(len(dfs)):
    reps={a:unidecode(a).lower() for a in list(dfs[i])}
    dfs[i].rename(index=str,columns=reps, inplace=True)

In [162]:
reps_global={'entidad federativa':'entidad',
      'entidad de ocurrencia':'entidad','entidad de residencia':'entidad',
      'numero de casos confirmados de paludismo con prueba de gota gruesa positiva que fueron registrados':'numero de casos confirmados de paludismo',
      'tasa de mortalidad por tuberculosis (todas las formas), defunciones por cada 100 mil habitantes':'tasa de mortalidad por tuberculosis',
      'tasa de incidencia asociada a la tuberculosis (todas las formas) por 100 mil habitantes':'tasa de incidencia asociada a la tuberculosis',
      'numero de casos confirmados para fiebre hemorragica por dengue confirmados por laboratorio':'numero de confirmados para fiebre hemorragica por dengue'
            }
for i in range(len(dfs)):
    dfs[i].rename(index=str,columns=reps_global, inplace=True)
    
list(dfs[9])

['periodo',
 'entidad',
 'numero de denfunciones por fiebre hemorragica por dengue',
 'numero de confirmados para fiebre hemorragica por dengue',
 'tasa de letalidad por 100 por dengue']

In [163]:
#check that entidad y periodo are on all data frames
for df in dfs:
    if ('entidad' not in list(df)) and ('periodo' not in list(df)):
        print('Alarm')
        print(df.head(0))

In [164]:
#check that entidad y periodo are on all data frames

master_df=dfs[0]

for df in dfs[1:]:
    common_columns=[]
    for element in list(master_df):
        if element in list(df): common_columns.append(element)
    master_df=pd.merge(master_df, df, on=common_columns)

In [165]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 420 entries, 0 to 419
Data columns (total 39 columns):
periodo                                                             420 non-null int64
entidad                                                             420 non-null object
defunciones por cancer de prostata                                  420 non-null int64
poblacion total masculina                                           420 non-null int64
tasa de mortalidad por cancer de prostata                           420 non-null float64
defunciones por suicidio                                            420 non-null int64
poblacion total adolescente                                         420 non-null int64
tasa de mortalidad por suicidio                                     420 non-null float64
numero de casos confirmados de paludismo                            420 non-null int64
poblacion total                                                     420 non-null int64
tasa de incidencia asociada al paludismo por 100 mil habitantes     420 non-null float64
defunciones por diabetes tipo ii                                    420 non-null int64
tasa de mortalidad por diabetes tipo ii                             420 non-null float64
casos confirmados de tuberculosis                                   420 non-null int64
tasa de incidencia asociada a la tuberculosis                       420 non-null float64
defunciones neonatales estimadas                                    420 non-null int64
nacimientos                                                         420 non-null int64
tasa de mortalidad neonatal                                         420 non-null float64
defunciones por enfermedades cardiovasculares                       420 non-null int64
tasa de mortalidad por enfermedades cardiovasculares                420 non-null float64
defunciones por epoc                                                420 non-null int64
tasa de mortalidad por epoc                                         420 non-null float64
defunciones por cancer de mama                                      420 non-null int64
poblacion femenina total                                            420 non-null int64
tasa de mortalidad por cancer de mama                               420 non-null float64
numero de denfunciones por fiebre hemorragica por dengue            420 non-null int64
numero de confirmados para fiebre hemorragica por dengue            420 non-null int64
tasa de letalidad por 100 por dengue                                420 non-null float64
tasa de mortalidad por tuberculosis                                 420 non-null float64
defunciones por cualquier tipo de tuberculosis                      420 non-null int64
defunciones por neoplasias malignas                                 420 non-null int64
tasa de mortalidad por neoplasias malignas                          420 non-null float64
tasa de mortalidad en ninos menores de 5 anos                       420 non-null float64
defunciones en la poblacion menor de 5 anos de edad                 420 non-null int64
nacidos vivos                                                       420 non-null int64
tasa de mortalidad por vih/sida (por 100 mil habitantes)            420 non-null float64
defunciones por vih/sida                                            420 non-null int64
defunciones por accidente de trafico de vehiculo de motor           420 non-null int64
tasa de mortalidad por accidente de trafico de vehiculo de motor    420 non-null float64
dtypes: float64(15), int64(23), object(1)
memory usage: 131.2+ KB

In [166]:
master_df.head(32)

,periodo,entidad,defunciones por cancer de prostata,poblacion total masculina,tasa de mortalidad por cancer de prostata,defunciones por suicidio,poblacion total adolescente,tasa de mortalidad por suicidio,numero de casos confirmados de paludismo,poblacion total,...,defunciones por cualquier tipo de tuberculosis,defunciones por neoplasias malignas,tasa de mortalidad por neoplasias malignas,tasa de mortalidad en ninos menores de 5 anos,defunciones en la poblacion menor de 5 anos de edad,nacidos vivos,tasa de mortalidad por vih/sida (por 100 mil habitantes),defunciones por vih/sida,defunciones por accidente de trafico de vehiculo de motor,tasa de mortalidad por accidente de trafico de vehiculo de motor
0,1998,Aguascalientes,33,70737,46.651682,10,396586,2.521521,0,974940,...,26,499,51.182637,21.710381,591,27222,2.359120,23,78,8.000492
1,1998,Baja California,89,166624,53.413674,46,987402,4.658690,0,2387650,...,196,1354,56.708479,27.653073,1466,53014,8.669612,207,293,12.271480
2,1998,Baja California Sur,16,33306,48.039392,13,184298,7.053793,0,439911,...,20,242,55.011127,20.511758,198,9653,4.319055,19,119,27.050926
3,1998,Campeche,21,60256,34.851301,31,268559,11.543087,51,673672,...,16,348,51.657186,22.799875,364,15965,3.859445,26,111,16.476861
4,1998,Colima,25,48296,51.764121,11,214935,5.117826,0,538560,...,26,321,59.603387,21.338742,263,12325,5.199049,28,74,13.740345
5,1998,Chiapas,69,315192,21.891419,40,1601849,2.497114,5224,3994325,...,349,1603,40.131937,38.511550,4798,124586,2.503552,100,355,8.887609
6,1998,Chihuahua,106,234953,45.115406,112,1156342,9.685716,331,2868346,...,159,1864,64.985187,27.862725,1804,64746,3.242287,93,376,13.108600
7,1998,Distrito Federal,461,804204,57.323764,214,3490225,6.131410,0,8912913,...,156,6240,70.010781,19.593627,3189,162757,8.672810,773,1251,14.035815
8,1998,Durango,79,126531,62.435293,25,597148,4.186567,53,1482259,...,51,777,52.419989,23.656684,925,39101,1.551686,23,174,11.738839
9,1998,Guanajuato,163,394425,41.325981,118,2110640,5.590721,0,5074849,...,90,2202,43.390454,27.275155,3574,131035,1.753747,89,876,17.261597
10,1998,Guerrero,73,283810,25.721433,37,1243128,2.976363,141,3204303,...,151,1136,35.452328,34.791422,3261,93730,4.587581,147,362,11.297309
11,1998,Hidalgo,49,207421,23.623452,23,943270,2.438326,4,2359558,...,92,1029,43.609863,30.565157,1795,58727,1.652852,39,298,12.629484
12,1998,Jalisco,314,545090,57.605166,149,2575925,5.784330,37,6401411,...,168,4005,62.564332,22.701681,3508,154526,5.670625,363,1307,20.417374
13,1998,México,299,890687,33.569593,140,5069773,2.761465,0,12424077,...,262,5082,40.904447,28.843301,8748,303294,3.863466,480,1518,12.218211
14,1998,Morelos,61,144156,42.315270,25,609643,4.100761,1,1566306,...,61,863,55.097791,22.772844,795,34910,5.682159,89,223,14.237320
15,1998,Nayarit,40,92739,43.131800,11,365258,3.011570,170,925239,...,59,578,62.470345,23.029145,482,20930,3.674726,34,188,20.319074
16,1998,Nuevo León,149,317100,46.988332,54,1551075,3.481456,1,3806709,...,191,2400,63.046584,17.007620,1415,83198,3.914142,149,310,8.143517
17,1998,Oaxaca,80,347871,22.997031,19,1394731,1.362270,17520,3623477,...,261,1686,46.529894,37.877039,3609,95282,3.532519,128,522,14.406053
18,1998,Puebla,142,418338,33.943844,66,2043906,3.229111,1,5113198,...,180,2286,44.707833,35.524297,4955,139482,4.341706,222,707,13.826963
19,1998,Quintana Roo,13,49210,26.417395,22,384791,5.717389,59,862418,...,15,240,27.828733,23.373407,453,19381,4.174310,36,124,14.378179
20,1998,San Luis Potosí,106,221438,47.868929,38,926866,4.099838,1,2367678,...,136,1242,52.456457,27.641257,1676,60634,1.520477,36,285,12.037110
21,1998,Sinaloa,115,222033,51.794103,37,994598,3.720096,764,2481249,...,122,1648,66.418163,19.277631,1155,59914,2.780858,69,506,20.392955
22,1998,Sonora,81,191343,42.332356,56,869920,6.437374,2,2203557,...,99,1523,69.115525,22.565688,1168,51760,2.677489,59,481,21.828344
23,1998,Tabasco,85,150206,56.588951,65,791928,8.207817,392,1914591,...,117,897,46.850737,25.126030,1256,49988,4.491821,86,274,14.311151
24,1998,Tamaulipas,103,228181,45.139604,65,1070449,6.072218,0,2671744,...,140,1643,61.495413,22.082331,1340,60682,2.545154,68,611,22.868958
25,1998,Tlaxcala,21,80836,25.978524,19,390257,4.868587,0,973084,...,23,382,39.256631,32.865823,860,26167,2.671917,26,100,10.276605
26,1998,Yucatán,57,163401,34.883507,34,652205,5.213085,7,1668680,...,69,1008,60.407028,21.675454,851,39261,5.633195,94,187,11.206463
27,1998,Zacatecas,62,133062,46.594820,17,578908,2.936563,0,1425943,...,31,846,59.329160,25.180265,887,35226,0.841548,12,254,17.812774
28,1999,Aguascalientes,32,73429,43.579512,17,400026,4.249724,0,991858,...,22,484,48.797308,20.731483,564,27205,2.621343,26,84,8.468954
29,1999,Baja California,76,176015,43.178138,40,1011406,3.954891,0,2469220,...,181,1324,53.620172,26.670187,1414,53018,9.476677,234,271,10.975126
30,1999,Baja California Sur,23,35219,65.305659,5,188203,2.656706,0,453340,...,13,254,56.028588,19.831484,193,9732,3.308775,15,111,24.484934
31,1999,Campeche,16,62047,25.786903,20,273470,7.313416,63,687422,...,15,319,46.405265,21.974542,347,15791,2.909421,20,106,15.419931

In [167]:
Dengue=['numero de denfunciones por fiebre hemorragica por dengue',
'numero de confirmados para fiebre hemorragica por dengue',
'tasa de letalidad por 100 por dengue']
master_df[Dengue]

,numero de denfunciones por fiebre hemorragica por dengue,numero de confirmados para fiebre hemorragica por dengue,tasa de letalidad por 100 por dengue
0,0,0,0.000000
1,0,0,0.000000
2,0,0,0.000000
3,0,0,0.000000
4,0,0,0.000000
5,0,2,0.000000
6,0,0,0.000000
7,0,0,0.000000
8,0,0,0.000000
9,0,0,0.000000
10,0,9,0.000000
11,0,3,0.000000
12,0,0,0.000000
13,0,0,0.000000
14,0,41,0.000000
15,0,0,0.000000
16,0,85,0.000000
17,0,20,0.000000
18,0,1,0.000000
19,0,0,0.000000
20,8,55,14.545455
21,0,6,0.000000
22,0,0,0.000000
23,0,0,0.000000
24,3,105,2.857143
25,0,0,0.000000
26,0,0,0.000000
27,0,0,0.000000
28,0,0,0.000000
29,0,0,0.000000
...,...,...,...
390,25,2099,1.191043
391,0,0,0.000000
392,0,0,0.000000
393,0,0,0.000000
394,0,14,0.000000
395,9,498,1.807229
396,0,53,0.000000
397,10,2086,0.479386
398,0,0,0.000000
399,0,0,0.000000
400,0,0,0.000000
401,0,0,0.000000
402,19,1915,0.992167
403,2,27,7.407407
404,0,63,0.000000
405,1,1,100.000000
406,12,1674,0.716846
407,0,1,0.000000
408,0,64,0.000000
409,19,1012,1.877470
410,0,28,0.000000
411,7,752,0.930851
412,1,163,0.613497
413,0,63,0.000000
414,7,41,17.073171
415,21,1303,1.611665
416,0,558,0.000000
417,0,0,0.000000
418,19,2805,0.677362
419,0,0,0.000000

In [169]:
dfs[1]

,periodo,entidad,defunciones por suicidio,poblacion total adolescente,tasa de mortalidad por suicidio
0,1990,Aguascalientes,6,355305,1.688690
1,1990,Baja California,18,763389,2.357907
2,1990,Baja California Sur,4,147342,2.714772
3,1990,Campeche,21,222944,9.419406
4,1990,Coahuila de Zaragoza,26,862446,3.014681
5,1990,Colima,7,195337,3.583550
6,1990,Chiapas,15,1322249,1.134431
7,1990,Chihuahua,40,1042097,3.838414
8,1990,Distrito Federal,119,3687359,3.227242
9,1990,Durango,13,596094,2.180864
10,1990,Guanajuato,40,2016582,1.983554
11,1990,Guerrero,7,1230170,0.569027
12,1990,Hidalgo,8,932600,0.857817
13,1990,Jalisco,70,2407716,2.907320
14,1990,México,57,4384999,1.299886
15,1990,Michoacán de Ocampo,37,1655642,2.234783
16,1990,Morelos,8,578795,1.382182
17,1990,Nayarit,7,347506,2.014354
18,1990,Nuevo León,27,1407170,1.918745
19,1990,Oaxaca,15,1319486,1.136806
20,1990,Puebla,20,1843494,1.084896
21,1990,Querétaro de Arteaga,11,532168,2.067016
22,1990,Quintana Roo,18,252878,7.118057
23,1990,San Luis Potosí,27,909452,2.968821
24,1990,Sinaloa,20,942306,2.122453
25,1990,Sonora,30,779730,3.847486
26,1990,Tabasco,67,687257,9.748900
27,1990,Tamaulipas,34,956188,3.555786
28,1990,Tlaxcala,7,334763,2.091032
29,1990,Veracruz Llave,65,2714011,2.394979
...,...,...,...,...,...
762,2013,Campeche,35,321369,10.890907
763,2013,Coahuila de Zaragoza,70,1019856,6.863714
764,2013,Colima,19,247781,7.668062
765,2013,Chiapas,140,2031757,6.890588
766,2013,Chihuahua,136,1266800,10.735712
767,2013,Distrito Federal,194,2832281,6.849603
768,2013,Durango,34,637114,5.336565
769,2013,Guanajuato,194,2143656,9.049960
770,2013,Guerrero,56,1352011,4.141978
771,2013,Hidalgo,44,1001623,4.392870
772,2013,Jalisco,216,2797029,7.722480
773,2013,México,326,5817882,5.603414
774,2013,Michoacán de Ocampo,66,1667434,3.958178
775,2013,Morelos,23,659941,3.485160
776,2013,Nayarit,21,417922,5.024861
777,2013,Nuevo León,92,1684744,5.460770
778,2013,Oaxaca,54,1460708,3.696837
779,2013,Puebla,103,2264246,4.548976
780,2013,Querétaro de Arteaga,56,722608,7.749707
781,2013,Quintana Roo,61,559000,10.912343
782,2013,San Luis Potosí,70,989817,7.072014
783,2013,Sinaloa,43,1038268,4.141513
784,2013,Sonora,80,998830,8.009371
785,2013,Tabasco,66,861891,7.657581
786,2013,Tamaulipas,58,1193312,4.860422
787,2013,Tlaxcala,22,459361,4.789262
788,2013,Veracruz Llave,108,2800760,3.856096
789,2013,Yucatán,66,738085,8.942060
790,2013,Zacatecas,22,563828,3.901899
791,2013,Nacional,2577,42499831,6.063554

In [20]:
#df_oax=df[df['Entidad federativa']=='Oaxaca']

In [21]:
#df_oax.iplot(kind='line',x='Periodo',y='Tasa de incidencia asociada a la tuberculosis (todas las formas) por 100 mil habitantes',mode='lines',size=10)

In [22]:
#df_oax.iplot(kind='line',x='Periodo',y='Casos confirmados de tuberculosis',mode='lines',size=10)

In [171]:
dfs[8]['entidad'].unique()

array(['Aguascalientes', 'Baja California', 'Baja California Sur',
       'Campeche', 'Coahuila de Zaragoza', 'Colima', 'Chiapas',
       'Chihuahua', 'Distrito Federal', 'Durango', 'Guanajuato',
       'Guerrero', 'Hidalgo', 'Jalisco', 'México', 'Michoacán de Ocampo',
       'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla',
       'Querétaro de Arteaga', 'Quintana Roo', 'San Luis Potosí',
       'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala',
       'Veracruz Llave', 'Yucatán', 'Zacatecas', 'Nacional'], dtype=object)

In [174]:
df_df=dfs[8][dfs[8]['entidad']=='Puebla']

df_df.iplot(kind='line',x='periodo',y='tasa de mortalidad por cancer de mama',mode='lines',size=10)

df_df=dfs[8][dfs[8]['entidad']=='Oaxaca']
df_df.iplot(kind='line',x='periodo',y='tasa de mortalidad por cancer de mama',mode='lines',size=10)

In [185]:
list_entidades=list(dfs[8]['entidad'].unique())

33

In [202]:

list_entidades=list(dfs[8]['entidad'].unique())


# Create traces
traces=[]
for entidad in list_entidades:
    trace = go.Scatter(
        x = dfs[8][dfs[8]['entidad']==entidad]['periodo'],
        y = dfs[8][dfs[8]['entidad']==entidad]['tasa de mortalidad por cancer de mama'],
        mode = 'lines+markers',
        name = str(entidad)
    )
    traces.append(trace)

In [206]:
list_entidades.index('Nacional')

32

In [212]:
iplot(traces[31:34], filename='scatter-mode')

In [213]:
dfs[8].head(1)

,periodo,entidad,defunciones por cancer de mama,poblacion femenina total,tasa de mortalidad por cancer de mama
0,1990,Aguascalientes,29,159967,18.128739

In [216]:
29/159967*100000

18.128739052429562